In [12]:
import spacy

from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import CountVectorizer

In [13]:
nlp = spacy.load("en_core_web_sm")

In [14]:
print(nlp.component_names)

['tok2vec', 'tagger', 'parser', 'senter', 'attribute_ruler', 'lemmatizer', 'ner']


## Similarity

In [59]:
nlp = spacy.load("en_core_web_sm")

In [60]:
# Define target to match to.
target = "certain"

In [61]:
# Define documents to match.
docs = [
    "certain",
    "sure",
    "uncertain",
]

In [62]:
# Vectorizer to convert to numeric data.
vectorizer = CountVectorizer().fit(docs)
vectorizer.vocabulary_

{'certain': 0, 'sure': 1, 'uncertain': 2}

In [63]:
# Transform the target.
target_vector = vectorizer.transform([target])
target_vector.todense()

matrix([[1, 0, 0]], dtype=int64)

In [64]:
# Transform the documents.
doc_vectors = vectorizer.transform(docs)
doc_vectors.todense()

matrix([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]], dtype=int64)

In [65]:
# Compute similarities.
for doc, doc_vector in zip(docs, doc_vectors):
    similarity = cosine_similarity(target_vector, doc_vector)[0 ,0]
    print(f"Similarity {target} - {doc:10s} {similarity:.2f}")

Similarity certain - certain    1.00
Similarity certain - sure       0.00
Similarity certain - uncertain  0.00


In [66]:
# Transform the target.
target_vector = nlp(target).vector.reshape(1, -1)
target_vector

array([[-1.2895280e+00, -1.1395018e+00, -1.2540374e+00, -5.4855835e-01,
        -1.1595764e+00, -3.8935116e-01,  6.4271963e-01,  1.3950783e-01,
         3.4786415e-01, -9.4651955e-01,  1.0652174e+00, -7.7924985e-01,
         2.5584698e-03,  1.2937251e+00, -1.8715000e+00, -3.9762202e-01,
        -1.2180480e+00, -1.3220410e+00,  3.1326032e-01,  6.7836034e-01,
        -1.3861450e+00,  7.2651041e-01, -7.1792394e-01,  4.1917363e-01,
        -4.5256519e-01,  9.9241471e-01, -4.0479362e-01,  1.8703582e+00,
        -1.3967817e+00, -1.6813838e-01,  5.4492760e-01, -4.6898928e-01,
         4.2342675e-01, -2.6025525e-01,  3.1247386e-01, -1.5594314e+00,
         1.7048987e+00, -6.5599269e-01,  2.1371987e+00,  1.1254809e+00,
        -1.2356936e+00, -1.2849273e-01,  6.0053176e-01,  7.8376961e-01,
         5.6471741e-01, -5.9699100e-01, -8.7788337e-01, -1.1115081e+00,
         3.3478615e-01,  5.8988518e-01,  4.1101146e-01,  1.2635951e+00,
        -4.0614787e-01,  5.8549511e-01,  5.0087643e-01,  2.01736

In [67]:
# Transform the documents.
doc_vectors = [nlp(doc).vector.reshape(1, -1) for doc in docs]

In [68]:
# Compute similarities.
for doc, doc_vector in zip(docs, doc_vectors):
    similarity = cosine_similarity(target_vector, doc_vector)[0 ,0]
    print(f"Similarity {target} - {doc:10s} {similarity:.2f}")

Similarity certain - certain    1.00
Similarity certain - sure       0.70
Similarity certain - uncertain  0.82


In [69]:
tmp = nlp("certain sure uncertain")

In [70]:
tmp[0].similarity(tmp[2])

C:\Users\lfkon\AppData\Local\Temp\ipykernel_13716\3759325553.py:1: UserWarning: [W007] The model you're using has no word vectors loaded, so the result of the Token.similarity method will be based on the tagger, parser and NER, which may not give useful similarity judgements. This may happen if you're using one of the small models, e.g. `en_core_web_sm`, which don't ship with word vectors and only use context-sensitive tensors. You can always add your own word vectors, or use one of the larger models instead if available.
  tmp[0].similarity(tmp[2])


0.5398919582366943

### Vector model

In [3]:
import spacy
import pandas as pd

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

In [5]:
# Load the IMDB review dataset.
reviews = pd.read_csv("../0_data/imdb/imdb_cleansed_zip.csv", compression="zip").sample(5000)
reviews.shape

(5000, 5)

In [11]:
reviews.columns

Index(['id', 'dataset', 'label', 'rating', 'content'], dtype='object')

In [10]:
reviews[["dataset", "label"]].value_counts(sort=False)

dataset  label   
Test     Negative    1255
         Positive    1243
Train    Negative    1226
         Positive    1276
Name: count, dtype: int64

In [13]:
nlp = spacy.load("en_core_web_md")
nlp.component_names

['tok2vec',
 'tagger',
 'parser',
 'senter',
 'attribute_ruler',
 'lemmatizer',
 'ner']

In [33]:
X_train = reviews.query("dataset == 'Train'")[["content"]]
y_train = reviews.query("dataset == 'Train'")["label"]

X_test = reviews.query("dataset == 'Test'")[["content"]]
y_test = reviews.query("dataset == 'Test'")["label"]

In [ ]:
def nlp_prep(dataset):
    return nlp.pipe(
        dataset,
        n_process=3,
        disable=[
            'tagger',
            'parser',
            'senter',
            'attribute_ruler',
            'lemmatizer',
            'ner'
        ]
    )

In [28]:
for dataset in X_train, X_test:
    dataset =
    )


In [32]:
type(X_train)

pandas.core.series.Series

In [16]:
model = RandomForestClassifier(n_jobs=3)

In [ ]:
model.fit(X, y)